### ISSUE TITLE
Export Empty as Base fails for Keys with Pluralization

### ISSUE THREAD

**Issue by unused** [lokalise/lokalise-cli-2-go#111]
Argument `--export-empty-as base` works well except for the case of pluralization. If a key is not translated at all, the base language will be used, even for keys with pluralization. If a pluralization is partly translated, the missing items do not use base values but an empty one. See the following example where `en` is the base locale, `fr` is not translated at all and `de` is missing a pluralization item. `de.test.pluralization.key.other` should be set with `Other`.

```yaml
en:
  test:
    pluralization:
      key:
        one: One
        other: Other
fr:
  test:
    pluralization:
      key:
        one: One
        other: Other
de:
  test:
    pluralization:
      key:
        one: Ein
        other: ''
```
