### ISSUE TITLE
Set flags in config file

### ISSUE THREAD

**Issue by mkaplan9** [lokalise/lokalise-cli-2-go#15]
Right now it seems like the config file doesn't support all of the possible flags. It would be nice to be able to do something like:
```
  file:
    download:
      project_id: 12345
      flags:
        format: json
        original-filenames: false
        <more_flags>
```
and then `lokalise2 file download --config lokalise.yml` would pull those in.
